server:
  port: 8080

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@user.ctcfm.mongodb.net/?retryWrites=true&w=majority&appName=User
      database: User
      auto-index-creation: true

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLong
  expiration: 3600000
  refresh-expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
