server:
  port: 8080

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000} # default nếu không có env
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
